# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_path <- function(Xd, statusd, rankmin, rankmax, order_mat, rev_order_mat, B0d, lambda_1_all, lambda_2_all, pfacd, step_sized = 1.0, niter = 2000L, linesearch_betad = 1.1, eps = 1e-5) {
    .Call(`_proxgpu_solve_path`, Xd, statusd, rankmin, rankmax, order_mat, rev_order_mat, B0d, lambda_1_all, lambda_2_all, pfacd, step_sized, niter, linesearch_betad, eps)
}

