# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator
# token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_path <- function(X, status, rankmin, rankmax, order, rev_order, B0, lambda_1_all, 
    lambda_2_all, pfac, step_sized = 1, niter = 2000L, linesearch_betad = 1.1, eps = 1e-05)
    {
    .Call(`_proxgpu_solve_path`, X, status, rankmin, rankmax, order, rev_order, B0, 
        lambda_1_all, lambda_2_all, pfac, step_sized, niter, linesearch_betad, eps)
}

